=== Pré-requis système

En fonction du type de gateway, des pré-requis peuvent être nécessaire. Ceux ci sont normalement pris en charge par l'installation du plugin.

'''
==== Serial Gateway

Jeedom pour pouvoir communiquer avec une Gateway sur port USB a besoin du module serialport pour nodejs.

Normalement cette installation est faite par le plugin lors de son activation.


'''
=== Configuration du plugin

La première étape de configuration se fait sur la page du plugin sur votre Jeedom maître.

Elle permettra de configurer la connexion avec la gateway.


'''
==== Configuration du mode

Plusieurs modes sont disponibles pour Rflink :

  *  Gateway sur Jeedom maître : pour utiliser le service controlleur en local (à choisir pour un gateway branchée localement)

  *  Gateway sur un Jeedom Esclave (la liste des esclaves apparait) : pour utiliser le controleur sur un Jeedom déporté (à choisir pour un gateway branchée sur un esclave)


'''
==== Configuration du port

Si on a choisi une connexion USB sur un Jeedom, la liste des ports est constituée de :

  *  la liste des périphériques USB branchés au Jeedom sélectionné, celle-ci est automatique

  *  la possibilité de choisir une connexion série (dans ce cas, il faudra remplir un champ libre avec le port)


'''
==== Configuration de l'inclusion

Ce choix permet de décider si le controleur va créer des nouveaux équipements Jeedom pour les périphériques détectés et inconnus.

En le passant en "désactivé", aucun nouvel équipement n'apparaitra dans Jeedom.

'''
=== Menu Rflink

Vous retrouverez toute la configuration des équipements (informations et commandes) dans le menu Plugins->Protocole domotique->Rflink

'''
==== Configuration des nodes et leurs capteurs

Les équipements Jeedom sont automatiquement créés au démarrage des nodes.

De la même facon que les équipements sont automatiquement créés à l'arrivée de nouveaux périphériques, les capteurs des nodes sont automatiquement créés comme des "Informations" dans Jeedom ainsi que les commandes RECUES (il faut créer des commandes dans ce cas).

'''
==== Configuration des commandes des nodes

Les commandes ne sont pas créées automatiquement.

Pour en créer une, il faut :

  * faire un ajout de commande action sur la page de l'équipement

  * puis il faut remplir le champ valeur en indiquant la bonne valeur SWITCH;CMD

  * SWITCH;CMD correspondant à la colonne capteur du signal qu'on souhaite reproduire

Exemple : si on a une information créée en appuyant sur le bouton 2 avec en valeur "2;OFF". Il faut rentrer ce "2;OFF" dans la valeur de la commande créée